### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/fhir-zulip-nlp-analysis#1]
## Description
_(Originally taken from: [Requirements google doc](https://docs.google.com/document/d/1s1hQCPL6LVYYTTEdT-L9tob9-SO7u0N8AykX4pR5-Fo/edit))_
Zulip Terminology Stream Text Mining Project

Base Zulip bulletin board application is supported by [a REST API](https://chat.fhir.org/api/rest) that can be interrogated (?) via Python scripts.  Bots can be configured via Python to provide real-time monitoring as well. Text mining of the [terminology stream in the FHIR Zulip community bulletin board ](https://chat.fhir.org/#narrow/stream/179202-terminology)to discover trends regarding use of terminologies and terminology services within the HL7 FHIR community.

Objective of this exercise is to review the history of the content and activity Terminology stream.

## Task list
- [ ] 1. Code systems: counts and date ranges
- [ ] 2. HL7 Product families: counts and date ranges
- [ ] 3. FHIR terminology resources: counts and date ranges
- [ ] 4. FHIR terminology operations: counts and date ranges
- [ ] 5. Indicators of JIRA activity: counts and date ranges
- [ ] 6a. Average length of threads
- [ ] 6b. Identify outlier threads in terms of length
- [ ] 6c. Threads lacking adequate resolution
- [ ] 6d. Frequency variance
- [ ] 6e. Activity variance

## Task details
_(Refer to for more info, especially for 1-5: [Requirements google doc](https://docs.google.com/document/d/1s1hQCPL6LVYYTTEdT-L9tob9-SO7u0N8AykX4pR5-Fo/edit))_

### 6a. Average length of threads
Determine _average length_ (in days / wells / months) in terminology stream threads.

### 6b. Identify outlier threads in terms of length
Identify _outliers_ in length - longer running threads

_Possible solutions:_
For this, can aggregate all thread lengths (i.e. in terms of number of messages) and report 2 different classes of identifiers: (i) 1 standard deviation away from norm, and (ii) 2 standard deviations.

### 6c. Threads lacking adequate resolution
Identify those topics with (i) _many responses_ (not necessarily with longer length, but will likely be one of these as well) that (ii) _do not have some sort of resolution_.  Will require iterative review with SME (Davera or others)

_Possible solutions:_
(i) **Many responses**: Can potentially be defined as 1 standard deviation away from mean.
(ii) **Lacking resolution**: This would likely be too time consuming to automate; so should go with suggestion of SME review. However, we could programmatically automate / aid this analysis, perhaps, by re-reading the analytical output. The output (likely a CSV file) could have 1+ codified curator columns, where data will be manually entered by SMEs. Then, that information could be re-read if further programmatic analysis is needed.

### 6d. Frequency variance
For each of the count categories (1-4) above, when is the occurrence of these topics, when are they _more frequent / less frequent_

### 6e. Activity variance
Date-base counts for all topics indicating activity levels: when is the stream _more active / less active_

**Comment by joeflack4** [comment]
@DaveraGabriel FYI

**Comment by stephanieshong** [comment]
We will assign this task to Rohan Hurer.

**Comment by stephanieshong** [comment]
#example of nlp keyword search that might be useful:

get_ipython().system('pip3 install --user nltk flashtext')

nltk.download('punkt')
from flashtext import KeywordProcessor

keyword_processor = KeywordProcessor()
keyword_dict = {
     "codesystem": ["DICOM","SNOMED", "LOINC", "ICD10CM", "ICD10PCS", "NDC", "RxNorm" ],
     "HL7Productfamilies": ["CDA", "C-CDA", "V3", "Version3"], 
     "TerminologyResources": ["ConceptMap", "CodeSystem","ValueSet","Terminology Service","TerminologyCapabilities", "NamingSystem", "Coding", "Code", "CodeableConcept"],
     "Operations": ["$lookup", "$validate-code", "$subsumes", "$find-matches", "$expand", "$validate-code", "$translate", "$closure"]
}

keyword_processor.add_keywords_from_dict(keyword_dict)
keyword_processor.extract_keywords('zulip activities based on code system, HL7Product family, Terminology Resources and Operations')

**Comment by joeflack4** [comment]
options
query topics one a a time: [<topic1>, <topic2>, ...]
query  topics after concatenating them together: <all_topics>
