### ISSUE TITLE
JIRA-related queries

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/fhir-zulip-nlp-analysis#35]
## Overview
Davera said:
It would be awesome to identify which messages mention JIRA or JIRA tickets.
You could generate a search in the string “JIRA” but better yet, also search for the inclusion of the HL7 base url into the JIRA instance indicating a message has a JIRA link in it. So: mentions if JIRA and also links to a JIRA page. In context of those searches, also whether that Zulip “resolved” check mark is used (I doubt much) withdraw be good.
_Re: that check mark… data re: when that check is used in the context of JIRA mentions or use will give us data to encourage adoption of a best practice by the community to use that checkmatk functionality. So that above is an additional search / data pull focus that will help us_

## Tasks
- [ ] 1. Add "JIRA" as new keyword. It belongs to (and is only member of) category also called "JIRA"
- [ ] 2. Context: "HL7 base url". (www.hl7.org?). This needs to be in the `context` field. 
- [ ] 3. Query JIRA tickets? Does Zulip API support regex? Or do we have to do straight NLP on messages? _(less important)_
- [ ] 4. Thread resolution: Check if boolean value is on for these threads. _(less important)_
