### ISSUE TITLE
Web app: Thread management an analysis

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/fhir-zulip-nlp-analysis#36]
## Overview
Davera said: 
> Outside of searches, something that would be helpful is an application that gives the ability to list individual message links based on input criteria so that these can be manually reviewed
> Example of this… messages that mention or have JIRA links. If I want to understand better what’s happening… I would like a list that allows me to step into each message matching that criteria. A “worklist” if matching messages.
> The JIRA search is more important than the list. But both would be awesome.

## Tasks
- [ ] 1. Set up a web application project
- [ ] 2. Set up deployment for the app
- [ ] 3. Page: Input selection -> Table display
- [ ] 4. Feature: "Step into" the message (little fuzzy on that still)

## Additional info
**Dependency: ** #35
