### ISSUE TITLE
Uncategorized misc TODOs

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/fhir-zulip-nlp-analysis#8]
## Summary
Just copy/pasting TODOs from Python code:
```
# TODO: In order to account for the possibility that people could edit their prior messages, can add as a param to this
#  ...function "account_for_edits"=True, or "cache"=False
# TODO: Add "as_of" field with today's date at the time we ran this script.
# TODO: spelling variations: v2 and V2 should be the same count, "Terminology Service" and
#  "Terminology Svc", "$lookup" and "lookup operation(s)", etc.
# TODO: keyword_variations: consider adding column to spreadsheet and using e.g. V2 variations would be "V2, Version 2"
```

Feel free to work on any of these if you have any additional time after #6 and #7 and want to do more

## Tasks
- [ ] 1. **Account for edits**: (probably time consuming to do)
- [x] 2. **Add `as_of`**: Can add this field to all of our CSVs (`df_raw` and the reports). The value for this should be the same for all rows. It should be today's date at the time that the script is run, formatted `YYYY-MM-DD`.
- [x] 3. **Spelling variations**: (probably time consuming to do)
- [x] 4. **Keyword variations**: I think this one is harder than (2) but easier than (1) and (3). Basically I'm thinking that we would convert this data structure:
```python
KEYWORDS = {
    'product_families': [
        'V2',
        'Version 2',
        'CDA',
        'C-CDA',
        'V3',
        'Version 3'
    ],
}
```
into this one:
```python
KEYWORDS = {
    'product_families': [
        ['V2', 'Version 2'],
        ['CDA'],
        ['C-CDA'],
        ['V3', 'Version 3'],
    ],
}
```
or this:
```python
KEYWORDS = {
    'product_families': {
        'V2': ['V2', 'Version 2'],
        'CDA': ['CDA'],
        'C-CDA': ['C-CDA'],
        'V3': ['V3', 'Version 3'],
    },
}
```
OR, and probably this is the best:
We update the [google sheet](https://docs.google.com/spreadsheets/d/1OB0CEAkOhVTN71uIhzCo_iNaiD1B6qLqL7uwil5O22Q/edit#gid=1136391153) with a column for the variations.

**Comment by joeflack4** [comment]
moved edits thing to: #24
